import 'package:get/get.dart';

// this class to translate the words to current language of user's device
class MyLocale implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    "ar": {
      "start": "ابدأ",
      "only": "فرد",
      "company": "شركة",
      "enter_your_phone": "أدخل رقم هاتفك",
      "phone_number": "رقم الهاتف",
      "password": "كلمة المرور",
      "missed_pass": "نسيت كلمة المرور؟",
      "or": "أو",
      "login": "تسجيل الدخول",
      "register_account": "تسجيل حساب",
      "register_new": "تسجيل حساب جديد",
      "register_only": "تسجيل",
      "register_company": "إنشاء حساب شركة",
      "enter_with": "دخول عن طريق",
      "enter_guest": "الدخول كزائر",
      "name": "الاسم",
      "email": "البريد الالكتروني",
      "enter_email": "أدخل بريدك الإلكتروني",
      "country": "الدولة",
      "choose_country": "أختر دولتك ",
      "confirm_pass": "تأكيد كلمة المرور ",
      "agree": "أوافق على ",
      "conditions": "الشروط والأحكام",
      "have_an_account": "لديك حساب؟ سجل دخول",
      "success": "تم انشاء حسابك بنجاح",
      "have_two": "لديك عدد (2) اعلان مجاني",
      "features": "مميزات انضمام المتجر",
      //
      "an_additional": "مصدر إضافي للأرباح",
      "get_more_orders": "احصل على المزيد من الطلبات",
      "new_customers": "زبائن جدد",
      "highlight_activity": "سلّط الضوء على نشاطك",
      "more_views": "مشاهدات أكثر",
      "unique_features": "مميزات فريدة للأنشطة التجارية",
      "join": "انضم",
      "company_name": "اسم الشركة",
      "company_active": "نشاط الشركة",
      "enter_name": "ادخل الاسم ",
      "whats_num": "رقم الواتساب",
      "enter_whats_num": "ادخل رقم الواتساب",
      "social_media_links": "روابط السوشيال ميديا",
      "pictures_store": "صور من المتجر",
      "write_a_summary": "يرجي كتابة نبذه عن نشاطك",
      "main": "الرئيسيه",
      "sections": "الأقسام",
      "post_ad": "أضف إعلانك",
      "my_ads": "إعلاناتي",
      "account": "حسابي",
      "loading_logo": "تحميل شعار الشركة",
      //
    },
    "en": {
      "start": "start",
      "only": "customer",
      "company": "company",
      "enter_your_phone": "enter your phone",
      "phone_number": "phone number",
      "password": "password",
      "missed_pass": "forget password",
      "login": "login",
      "register_new": "new register",
      "register_only": "register",
      "register_company": "register company",
      "enter_with": "enter with",
      "enter_guest": "enter as guest",
      "name": "name",
      "email": "email",
      "enter_email": "enter email",
      "country": "country",
      "choose_country": "choose country ",
      "confirm_pass": "confirm password",
      "agree": "agree",
      "have_an_account": "have an account",
      "success": "success",
      "have_two": "have two adv",
      "features": "features join to company",
      //
      "an_additional": "مصدر إضافي للأرباح",
      "get_more_orders": "احصل على المزيد من الطلبات",
      "new_customers": "زبائن جدد",
      "highlight_activity": "سلّط الضوء على نشاطك",
      "more_views": "مشاهدات أكثر",
      "unique_features": "مميزات فريدة للأنشطة التجارية",
      "join": "انضم",
      "company_name": "اسم الشركة",
      "enter_name": "ادخل الاسم ",
      "whats_num": "رقم الواتساب",
      "enter_whats_num": "ادخل رقم الواتساب",
      "social_media_links": "روابط السوشيال ميديا",
      "pictures_store": "صور من المتجر",
      "write_a_summary": "يرجي كتابة نبذه عن نشاطك",
      "main": "الرئيسيه",
      "sections": "الأقسام",
      "post_ad": "أضف إعلانك",
      "my_ads": "إعلاناتي",
      "account": "حسابي",
      "loading_logo": "تحميل شعار الشركة",
      //
    },
  };
}
